### ISSUE TITLE
Gadget server and cookie support

### ISSUE THREAD

**Issue by ericchu923** [andychucs/conning_tower#218]
**Is your feature request related to a problem? Please describe.**

* When login Kancolle with conning_tower , there will be 403 forbidden (or 200 ok but is white screen) at game page

**Describe the solution you'd like**

* Add cookie support and import KCWiki's gadget server (https://kcwiki.github.io/cache) to bypass regional blocks

**Describe alternatives you've considered**
* There are other way to fix this issue (such as OOI or acgpower) but I think this solution is simple

**Comment by andychucs** [comment]
I have checked [poi-plugin-let-me-in](https://github.com/kcwiki/poi-plugin-let-me-in),  use 3rd party cache should redirect url on iOS  that need a VPN service as I know.

ConningTower is a browser app and should not provide VPN services, as this would conflict with the VPN services already run on iOS and Android. The service may still be offered as part of this project in the future.

**Quantumult X and similar applications can implement URL redirects via rules. While unproven, it is suggested to use these popular web tools.**

If there is a way to implement this feature using the JavaScript console or by editing cookies, please let me know. It should be easy to implement.

<details>

<summary>P.S.</summary>

By the way not related to this open source project, it may needs to be stated here that the AppStore channel will never use `NEVPNManager API` ,  [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/#vpn-apps) request only organization developer use that. 
> Apps offering VPN services must utilize the [NEVPNManager API](https://developer.apple.com/documentation/networkextension/nevpnmanager/) and may only be offered by developers enrolled as an organization.

</details>

**Comment by ericchu923** [comment]
These Javascript codes are used to edit cookies when there is no Kancolle browser on iOS(Use Safari):

`javascript:document.cookie='ckcy=1;expires=Sun, 04 Feb 2029 09:00:09 GMT;domain=osapi.dmm.com;path=/';`

`javascript:document.cookie='ckcy=1;expires=Sun, 04 Feb 2029 09:00:09 GMT;domain=203.104.209.7;path=/';`

`javascript:document.cookie='ckcy=1;expires=Sun, 04 Feb 2029 09:00:09 GMT;domain=www.dmm.com;path=/netgame/';`

`javascript:document.cookie='ckcy=1;expires=Sun, 04 Feb 2029 09:00:09 GMT;domain=log-netgame.dmm.com;path=/';`

Still works now for me, hope it useful

**Comment by andychucs** [comment]
I have add a "Modify Cookie" button on web info page in [1.12.1+2 release](https://github.com/andychucs/conning_tower/releases/tag/v1.12.1%2B2). It looks not work well.
