### ISSUE TITLE
可以不用vpn就玩艦c嗎

### ISSUE THREAD

**Issue by GenjiWang** [andychucs/conning_tower#243]
請問有沒有免VPN玩艦C的方法

**Comment by andychucs** [comment]
https://github.com/andychucs/conning_tower/issues/218 这里提到的方法目前只能在Android上实现，秋雲改版本提供了modify cookie功能，但是我验证无效。所以目前回答是不能。有用户报告ooi.moe可以正常运行，但是我没有对ooi.moe进行适配，画面需要自行调整，可以尝试使用。同样也可以尝试Quantumult X等软件做redirect至kcwiki的GitHub快取，它们并非传统意义的VPN。
