### ISSUE TITLE
任務搜尋&艦隊導出功能

### ISSUE THREAD

**Issue by nightMORALS** [andychucs/conning_tower#311]
1.希望任務欄目（尤其是已完成任務欄）可以新增搜尋功能，方便查找什麼任務已完成或未完成。

2.希望可以新增將全艦娘&裝備內容導出的功能，用以上傳至制空權模擬器等網站，方便展示。

**Comment by andychucs** [comment]
1. duplicate: https://github.com/andychucs/conning_tower/issues/111
