### ISSUE TITLE
要是能加上绕过区域限制的功能就好了

### ISSUE THREAD

**Issue by rinnelin** [andychucs/conning_tower#358]
如题 就像kc3改的一样 ios没办法使用chrome插件有点头大 毕竟不是什么时候都用着能直接进游戏的v
参考https://github.com/kcwiki/cache
除了kc3那样加进去的 也有单独做的https://github.com/kcwiki/chrome-extension-dmm

**Comment by andychucs** [comment]
参考这里：https://github.com/andychucs/conning_tower/issues/243#issuecomment-2004257279

**Comment by rinnelin** [comment]
> 参考这里：[#243 (comment)](https://github.com/andychucs/conning_tower/issues/243#issuecomment-2004257279)

不是很懂相关方面折腾ss的重定向感觉好像方向是对的但是到了ios15以上不知道是不是因为要用那个javascript:[http://window.open](https://t.co/yW3qzOq2um)("http:"+gadgetInfo.URL,'_blank'); 导致怎么改都要么还是白屏要么404

**Comment by andychucs** [comment]
@rinnelin 舰桥在iOS上是直接提取osapi请求的URL后直接打开的，与直接打开的kcsapi的请求并没有什么区别，只要替换相应域名应该就可以解决游戏服务器的访问拒绝

**Comment by rinnelin** [comment]
> @rinnelin 舰桥在iOS上是直接提取osapi请求的URL后直接打开的，与直接打开的kcsapi的请求并没有什么区别，只要替换相应域名应该就可以解决游戏服务器的访问拒绝

我Safari和舰桥都试过了……最后看ss里原来url=http%3A%2F%2F203.104.209.7%2Fgadget_html5.xml都变成了url=http%3A%2F%2Fkcwiki.github.io/cache/%2Fgadget_html5.xml 但是还是不行 估计还是替换没完成好吧 算了……总之谢谢

**Comment by rinnelin** [comment]
虽然不是负责的项目不过我重新想了想 是不是因为ios15打开用的那个连接本质是把http部分单独窗口化  但是kcwiki是https结果导致又回到了http和https混杂的问题？毕竟那个脚本打开完最前面是http的osapi.dmm.com

**Comment by andychucs** [comment]
@rinnelin 我不确定是不是mix问题，也有可能是跨域问题，因为有其他工具的例子我想这种请求本身应该不会受到影响。
可以这样测试一下：osapi的打开方式在chrome上是通用的，现在的chrome也是默认禁止mix的，所以在chrome上用osapi链接打开游戏并使用kcwiki给出的几种缓存使用方法测试，就能知道这个方法是不是可行了。Mac上使用safari也可模拟iOS的情况。
